export const teamData = [
  {
    id: 1,
    name: "Yohannes D.",
    designation: "Founder & CEO",
    role: "Mobile App Developer | Web Developer | Tech Blogger",
    image: "/images/team/jo1.jpg",
    social: {
      telegram: "https://t.me/yoh_space",
      twitter: "https://twitter.com/yoh_space",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },
  {
    id: 2,
    name: "Yonas B.",
    designation: "Co-Founder & CTO",
    role: "Full Stack Web Developer",
    image: "",
    social: {
      telegram: "https://t.me/sugarhillny",
      twitter: "/about#",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },
   {
    id: 3,
    name: "Yohannes B.",
    designation: "Graphics Designer",
    role: "Graphics Designer | UI/UX Designer",
    image: "/images/team/yo.JPG",
    social: {
      telegram: "https://t.me/fourma",
      twitter: "/about#",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },
  {
    id: 4,
    name: "Davidson Z.",
    designation: "Video Editor & Social Media Manager",
    role: "Video Editing | Social Media Managment",
    image: "/images/team/david.jpg",
    social: {
      telegram: "https://t.me/sccot59",
      twitter: "https://x.com/Davidson5995",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },  
  {
    id: 5,
    name: "Nathaniel E.",
    designation: "Digital Marketing Manager",
    role: "Digital Marketing",
    image: "/images/team/nati.png",
    social: {
      telegram: "https://t.me/ersom1621",
      twitter: "/about#",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },
  {
    id: 6,
    name: "Meron A.",
    designation: "Junior Mobile App Developer",
    role: "Mobile App Developer",
    image: "",
    social: {
      telegram: "https://t.me/yoh_space",
      twitter: "/about#",
      linkedin: "/about#",
      youtube: "https://youtube.com/@yoh_space",
    },
  },
];