import { Menu } from "@/types/menu";
import { Home, Info, Phone, BookOpen, GraduationCap, FlaskConical, Users, FileText, Building2, Microscope, Globe } from "lucide-react";

const menuData: (Menu & { icon?: any })[] = [
  {
    id: 1,
    title: "Home",
    path: "/",
    newTab: false,
    icon: Home,
  },
  {
    id: 2,
    title: "About",
    newTab: false,
    icon: Info,
    submenu: [
      {
        id: 21,
        title: "Background",
        path: "/about/background",
        newTab: false,
        icon: Info,
      },
      {
        id: 22,
        title: "Vision & Mission",
        path: "/about/vision-mission",
        newTab: false,
        icon: Globe,
      },
      {
        id: 23,
        title: "Dean's Message",
        path: "/about/deans-message",
        newTab: false,
        icon: Users,
      },
      {
        id: 24,
        title: "Administration",
        path: "/about/administration",
        newTab: false,
        icon: Users,
      },
      {
        id: 25,
        title: "Structure",
        path: "/about/structure",
        newTab: false,
        icon: Building2,
      },
      {
        id: 26,
        title: "Stuffs",
        path: "/stuffs",
        newTab: false,
        icon: GraduationCap,
      },
      {
        id: 27,
        title: "Reports",
        path: "/about/reports",
        newTab: false,
        icon: FileText,
      },
    ],
  },
  {
    id: 3,
    title: "Academics",
    path: "/academics",
    newTab: false,
    icon: GraduationCap,
    submenu: [
      {
        id: 31,
        title: "Chemistry",
        path: "/academics/chemistry",
        newTab: false,
        icon: FlaskConical,
      },
      {
        id: 32,
        title: "Industrial Chemistry",
        path: "/academics/industrial-chemistry",
        newTab: false,
        icon: FlaskConical,
      },
      {
        id: 33,
        title: "Biology",
        path: "/academics/biology",
        newTab: false,
        icon: Microscope,
      },
      {
        id: 34,
        title: "Physics",
        path: "/academics/physics",
        newTab: false,
        icon: BookOpen,
      },
      {
        id: 35,
        title: "Mathematics",
        path: "/academics/mathematics",
        newTab: false,
        icon: BookOpen,
      },
      {
        id: 36,
        title: "Statistics",
        path: "/academics/statistics",
        newTab: false,
        icon: BookOpen,
      },
    ],
  },
  {
    id: 4,
    title: "Resources",
    path: "/resources",
    newTab: false,
    icon: Microscope,
    submenu: [
      {
        id: 41,
        title: "Research",
        path: "/resources/research",
        newTab: false,
        icon: Info,
      },
      {
        id: 42,
        title: "Publications",
        path: "/resources/publication",
        newTab: false,
        icon: FileText,
      },
    ],
  },
  {
    id: 5,
    title: "Services",
    path: "/services",
    newTab: false,
    icon: Building2,
    submenu: [
      {
        id: 51,
        title: "Laboratories",
        path: "/laboratories",
        newTab: false,
        icon: FlaskConical,
      },
      {
        id: 52,
        title: "Community Engagement",
        path: "/services",
        newTab: false,
        icon: Users,
      },
    ],
  },
  {
    id: 6,
    title: "Contact",
    path: "/contact",
    newTab: false,
    icon: Phone,
  },
];
export default menuData;
